from functools import partial
from pytdbot.filters import create
from re import compile as re_compile, match

from ..modules import *
from ..helper.telegram_helper.progress import tdlib_file_update
from ..helper.telegram_helper.bot_commands import BotCommands
from ..helper.telegram_helper.filters import CustomFilters, match_cmd
from .telegram_client import TgManager


def add_handlers():
    TgManager.bot.add_handler(
        "updateNewMessage",
        authorize,
        filters=create(
            partial(
                CustomFilters.sudo_user, pattern=match_cmd(BotCommands.AuthorizeCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        unauthorize,
        filters=create(
            partial(
                CustomFilters.sudo_user,
                pattern=match_cmd(BotCommands.UnAuthorizeCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        add_sudo,
        filters=create(
            partial(
                CustomFilters.owner_filter,
                pattern=match_cmd(BotCommands.AddSudoCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        remove_sudo,
        filters=create(
            partial(
                CustomFilters.owner_filter, pattern=match_cmd(BotCommands.RmSudoCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        send_bot_settings,
        filters=create(
            partial(
                CustomFilters.sudo_user, pattern=match_cmd(BotCommands.BotSetCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        cancel,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.CancelTaskCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        cancel_all_buttons,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.CancelAllCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        clone_node,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.CloneCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        aioexecute,
        filters=create(
            partial(
                CustomFilters.owner_filter, pattern=match_cmd(BotCommands.AExecCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        execute,
        filters=create(
            partial(
                CustomFilters.owner_filter, pattern=match_cmd(BotCommands.ExecCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        clear,
        filters=create(
            partial(
                CustomFilters.owner_filter,
                pattern=match_cmd(BotCommands.ClearLocalsCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        select,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.SelectCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        remove_from_queue,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.ForceStartCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        count_node,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.CountCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        delete_file,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.DeleteCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        gdrive_search,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.ListCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        mirror,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.MirrorCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        qb_mirror,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.QbMirrorCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        jd_mirror,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.JdMirrorCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        nzb_mirror,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.NzbMirrorCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        leech,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.LeechCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        qb_leech,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.QbLeechCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        jd_leech,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.JdLeechCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        nzb_leech,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.NzbLeechCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        get_rss_menu,
        filters=create(
            partial(
                CustomFilters.authorized_user, pattern=match_cmd(BotCommands.RssCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        run_shell,
        filters=create(
            partial(
                CustomFilters.owner_filter, pattern=match_cmd(BotCommands.ShellCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateMessageEdited",
        run_shell,
        filters=create(
            partial(
                CustomFilters.owner_filter, pattern=match_cmd(BotCommands.ShellCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        start,
        filters=create(
            partial(
                CustomFilters.public_user, pattern=match_cmd(BotCommands.StartCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        log,
        filters=create(
            partial(CustomFilters.sudo_user, pattern=match_cmd(BotCommands.LogCommand))
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        restart_bot,
        filters=create(
            partial(
                CustomFilters.sudo_user, pattern=match_cmd(BotCommands.RestartCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        ping,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.PingCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        bot_help,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.HelpCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        bot_stats,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.StatsCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        task_status,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.StatusCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        torrent_search,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.SearchCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        get_users_settings,
        filters=create(
            partial(
                CustomFilters.sudo_user, pattern=match_cmd(BotCommands.UsersCommand)
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        send_user_settings,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.UserSetCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        ytdl,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.YtdlCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        ytdl_leech,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.YtdlLeechCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewMessage",
        hydra_search,
        filters=create(
            partial(
                CustomFilters.authorized_user,
                pattern=match_cmd(BotCommands.NzbSearchCommand),
            )
        ),
        inner_object=True,
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        edit_bot_settings,
        filters=create(
            partial(CustomFilters.sudo_user, pattern=re_compile("^botset "))
        ),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        confirm_restart,
        filters=create(
            partial(CustomFilters.sudo_user, pattern=re_compile("^botrestart "))
        ),
    )
    TgManager.bot.add_handler("UpdateFile", tdlib_file_update)
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        cancel_all_update,
        filters=create(lambda _, e: match("^canall ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        cancel_multi,
        filters=create(lambda _, e: match("^stopm ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        edit_user_settings,
        filters=create(lambda _, e: match("^userset ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        torrent_search_update,
        filters=create(lambda _, e: match("^torser ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        status_pages,
        filters=create(lambda _, e: match("^status ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        rss_listener,
        filters=create(lambda _, e: match("^rss ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        confirm_selection,
        filters=create(lambda _, e: match("^sel ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        select_type,
        filters=create(lambda _, e: match("^list_types ", e.text)),
    )
    TgManager.bot.add_handler(
        "updateNewCallbackQuery",
        arg_usage,
        filters=create(lambda _, e: match("^help ", e.text)),
    )
