class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mir1'
        self.UnzipMirrorCommand = 'unzipmir1'
        self.ZipMirrorCommand = 'zipmir1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'listli'
        self.SearchCommand = 'searchse'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = ["clone1","gdtot1","g"]
        self.CountCommand = 'count'
        self.WatchCommand = 'watch1'
        self.ZipWatchCommand = 'zipwatch1'
        self.QbMirrorCommand = 'qbmir'
        self.QbUnzipMirrorCommand = 'qbunzipmir1'
        self.QbZipMirrorCommand = 'qbzipmir1'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.LeechSetCommand = 'leechset22'
        self.SetThumbCommand = 'setthumbQ'
        self.LeechCommand = 'leechq'
        self.UnzipLeechCommand = 'unzipleechq'
        self.ZipLeechCommand = 'zipleechq'
        self.QbLeechCommand = 'qbleechq'
        self.QbUnzipLeechCommand = 'qbunzipleechq'
        self.QbZipLeechCommand = 'qbzipleechq'
        self.LeechWatchCommand = 'leechwatchq'
        self.LeechZipWatchCommand = 'leechzipwatqch'
        self.RssListCommand = 'rsslist'
        self.RssGetCommand = 'rssget'
        self.RssSubCommand = 'rsssub'
        self.RssUnSubCommand = 'rssunsub'
        self.RssUnSubAllCommand = 'rssunsuball'

BotCommands = _BotCommands()

#credits Me 
